# Generated by Django 6.0.4 on 2026-06-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_topic_createpost_is_featured_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_covers/'),
        ),
    ]
